var dummy: Array = [
			ScrollArrowDown_disabledSkin,
			ScrollArrowDown_upSkin,
			ScrollArrowDown_downSkin,
			ScrollArrowDown_overSkin,
			ScrollArrowUp_disabledSkin,
			ScrollArrowUp_upSkin,
			ScrollArrowUp_downSkin,
			ScrollArrowUp_overSkin,
			
			ScrollTrack_skin,
			ScrollThumb_upSkin,
			ScrollThumb_downSkin,
			ScrollThumb_overSkin,
			ScrollPane_upSkin,
			
			Button_overSkin,
			Button_upSkin,
			Button_downSkin,
			Button_selectedOverSkin,
			Button_selectedUpSkin,
			Button_selectedDownSkin,
			
			MenuSkin,
			MenuCellRenderer_overSkin,
			MenuCellRenderer_upSkin,
			MenuCellRenderer_downSkin,
			MenuCellRenderer_selectedOverSkin,
			MenuCellRenderer_selectedUpSkin,
			MenuCellRenderer_selectedDownSkin,
			
			TextArea_upSkin,
			TextArea_disabledSkin,
			
			List_skin,
			
			CellRenderer_upSkin,
			CellRenderer_overSkin,
			CellRenderer_downSkin,
			
			CellRenderer_selectedUpSkin,
			CellRenderer_selectedOverSkin,
			CellRenderer_selectedDownSkin,
			
			DataGrid_skin,
			HeaderRenderer_upSkin,
			HeaderRenderer_overSkin,
			HeaderRenderer_downSkin,
			HeaderRenderer_selectedUpSkin,
			HeaderRenderer_selectedOverSkin,
			HeaderRenderer_selectedDownSkin,
			
			ColumnStretch_cursor,
			
			SliderThumb_disabledSkin,
			SliderThumb_downSkin,
			SliderThumb_overSkin,
			SliderThumb_upSkin,
			SliderTick_skin,
			SliderTrack_disabledSkin,
			SliderTrack_skin,
			CheckBox_upIcon,
			CheckBox_downIcon,
			CheckBox_overIcon,
			CheckBox_disabledIcon,
			CheckBox_selectedDisabledIcon,
			CheckBox_selectedUpIcon,
			CheckBox_selectedDownIcon,
			CheckBox_selectedOverIcon,
			ComboBox_upSkin,
			ComboBox_overSkin,
			ComboBox_downSkin,
			ComboBox_disabledSkin,
		   ];